const Opcode = {
  PING: 1,
  DEBUG: 2,
  RECONNECT: 3,
  LOG: 5,
  SESSION_INIT: 6,
  PROFILE: 16,
  AUTH_REQUEST: 17,
  AUTH: 18,
  AUTH_LOGIN_CHECK_PASSWORD: 0x73,
  LOGIN: 19,
  LOGOUT: 20,
  SYNC: 21,
  CONFIG: 22,
  CONTACT_INFO: 32,
  CONTACT_UPDATE: 34,
  CONTACT_INFO_BY_PHONE: 46,
  CHAT_INFO: 48,
  CHAT_HISTORY: 49,
  CHAT_MARK: 50,
  CHATS_LIST: 53,
  CHAT_UPDATE: 55,
  CHAT_JOIN: 57,
  CHAT_LEAVE: 58,
  CHAT_MEMBERS: 59,
  MSG_SEND: 64,
  UPLOAD_ATTACH_PREP: 65,
  MSG_DELETE: 66,
  MSG_EDIT: 67,
  CHAT_SUBSCRIBE: 75,
  CHAT_MEMBERS_UPDATE: 77,
  PHOTO_UPLOAD: 80,
  VIDEO_UPLOAD: 82,
  VIDEO_PLAY: 83,
  FILE_UPLOAD: 87,
  FILE_DOWNLOAD: 88,
  LINK_INFO: 89,
  SESSIONS_INFO: 96,
  SESSIONS_CLOSE: 97,
  AUTH_2FA_DETAILS: 0x68,
  AUTH_SET_2FA: 0x6f,
  NOTIF_MESSAGE: 128,
  NOTIF_CHAT: 135,
  NOTIF_ATTACH: 136,
  NOTIF_INCOMING_CALL: 137,
  NOTIF_MSG_DELETE: 154,
  NOTIF_MSG_REACTIONS_CHANGED: 155,
  MSG_REACTION: 178,
  MSG_CANCEL_REACTION: 179,
  MSG_GET_REACTIONS: 180,
  FOLDERS_GET: 272,
  FOLDERS_UPDATE: 274,
  FOLDERS_DELETE: 276,
  GET_QR: 288,
  GET_QR_STATUS: 289,
  AUTH_QR_APPROVE: 290,
  LOGIN_BY_QR: 291,
};

const OpcodeNames = {};
for (const [name, code] of Object.entries(Opcode)) {
  OpcodeNames[code] = name;
}

function getOpcodeName(code) {
  return OpcodeNames[code] || `UNKNOWN_${code}`;
}

const DeviceType = {
  WEB: 'WEB',
};

module.exports = {
  Opcode,
  DeviceType,
  getOpcodeName,
};

